# Generated by Django 2.1.4 on 2019-07-25 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190717_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('1', '男性'), ('2', '女性')], max_length=1)),
                ('birth', models.DateField(blank=True)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=9)),
                ('image', models.ImageField(blank=True, upload_to='image/user/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
