# Generated by Django 2.1.4 on 2019-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20190729_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='photo', to='contents.Image'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='thumbnail',
            field=models.ManyToManyField(blank=True, related_name='thumbnail', to='contents.Image'),
        ),
    ]
